export const adminConstants = {
  CREATE_WALLET_SUCCESS: "CREATE_WALLET_SUCCESS",
  CREATE_WALLET_FAILURE: "CREATE_WALLET_FAILURE",
  CREATE_WALLET_PROGRESS: "CREATE_WALLET_PROGRESS",

  QUERY_ACTIVITIES_PROGRESS: "QUERY_ACTIVITIES_PROGRESS",
  QUERY_ACTIVITIES_SUCCESS: "QUERY_ACTIVITIES_SUCCESS",
  QUERY_ACTIVITIES_FAILURE: "QUERY_ACTIVITIES_FAILURE",

  CREDIT_WALLET_PROGRESS: "CREDIT_WALLET_PROGRESS",
  CREDIT_WALLET_SUCCESS: "CREDIT_WALLET_SUCCESS",
  CREDIT_WALLET_FAILURE: "CREDIT_WALLET_FAILURE",

  DEBIT_WALLET_PROGRESS: "DEBIT_WALLET_PROGRESS",
  DEBIT_WALLET_SUCCESS: "DEBIT_WALLET_SUCCESS",
  DEBIT_WALLET_FAILURE: "DEBIT_WALLET_FAILURE",

  QUERY_WALLET_HISTORY_SUCCESS: "QUERY_WALLET_HISTORY_SUCCESS",
  QUERY_WALLET_HISTORY_FAILURE: "QUERY_WALLET_HISTORY_FAILURE",
  QUERY_WALLET_HISTORY_PROGRESS: "QUERY_WALLET_HISTORY_PROGRESS",

  QUERY_WALLETS_SUCCESS: "QUERY_WALLETS_SUCCESS",
  QUERY_WALLETS_FAILURE: "QUERY_WALLETS_FAILURE",
  QUERY_WALLETS_PROGRESS: "QUERY_WALLETS_PROGRESS",

  LOGIN_PROGRESS: "LOGIN_PROGRESS",
  LOGIN_SUCCESS: "LOGIN_SUCCESS",
  LOGIN_FAILURE: "LOGIN_FAILURE",

  LOGOUT_PROGRESS: "LOGOUT_PROGRESS",
  LOGOUT_SUCCESS: "LOGOUT_SUCCESS",
  LOGOUT_FAILURE: "LOGOUT_FAILURE",
};
